FROM alpine AS build

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    ./proto/app.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
            --descriptor_set_out=app.pb app.proto

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/app.pb /tmp/