FROM --platform=linux/amd64 node:bookworm-slim
# platform flag is needed to run on Mac machines

WORKDIR /app

RUN apt update && apt install build-essential -y --no-install-recommends
RUN npm install -g @protobuf-ts/plugin protoc
COPY ./api/package*.json .

RUN npm install

COPY ./proto/machine.proto .

COPY ./api .
RUN npx protoc --ts_out ./src --proto_path . machine.proto
RUN npm run build

EXPOSE 8000
CMD ["node", "/app/src/index.js"]