version: "3.2"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 4173:4173
    stop_signal: SIGINT
    environment:
      - CENTER_LON
      - CENTER_LAT
      - MAP_X
      - MAP_Y
    depends_on:
      - api
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - backend
    environment:
      - CENTER_LON
      - CENTER_LAT
      - NUM_MACHINES
      - DELTA
      - NUM_STEPS
      - MAP_X
      - MAP_Y
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - server
    ports:
      - 8000:8000
    networks:
      - backend
networks:
  backend: