FROM python

WORKDIR /app

RUN apt update && apt install -y --no-install-recommends build-essential protobuf-compiler 
RUN pip3 install --upgrade pip

COPY ./server/requirements.txt .
RUN pip install -r requirements.txt
RUN pip install --upgrade protobuf

RUN mkdir -p proto
COPY ./proto/*.proto ./proto/
RUN python -m grpc_tools.protoc -I ./proto --python_out=. --grpc_python_out=. ./proto/machine.proto

COPY ./server/*.py .

EXPOSE 50051
CMD ["python3", "main.py"]