FROM node:current-alpine as build

WORKDIR /app

RUN apk add --no-cache protoc
RUN npm install -g protoc-gen-ts
COPY ./client/package*.json .

RUN npm install

COPY ./proto/machine.proto .

COPY ./client . 
RUN protoc -I=. --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_opt=unary_rpc_promise=true --ts_opt=target=web --ts_proto_opt=esModuleInterop=true --ts_out=./src machine.proto


COPY ./client . 

#RUN npm run build

EXPOSE 8081
CMD ["npm", "run", "preview"]